apiVersion: v1
kind: Secret
metadata:
  name: bds-manual-secrets
type: Opaque
stringData:
  BDS_CFG_BDS_GLOBALS_GWS_CLIENTID_PLACEHOLDER: your_api_client
  BDS_CFG_BDS_GLOBALS_GWS_CLIENT_SECRET_PLACEHOLDER: xxx
  BDS_CFG_BDS_GWS_CLIENTID_PLACEHOLDER: your_api_client
  BDS_CFG_BDS_GWS_CLIENT_SECRET_PLACEHOLDER: xxx
  BDS_CFG_CONSUL_TOKEN_PLACEHOLDER: your_consul_token
  BDS_CFG_CONSUL_URL_API_PLACEHOLDER: https://consul-server.infra.svc.cluster.local
  BDS_CFG_CONSUL_URL_API_REGION_PLACEHOLDER: https://consul-server.infra.svc.cluster.local
  BDS_CFG_CONSUL_WESTUS2_TOKEN_PLACEHOLDER: your_consul_token
  BDS_CFG_CONTACT_CENTER_ID_PLACEHOLDER: 9350e2fc-a1dd-4c65-8d40-1f75a2e080dd
  BDS_CFG_CS_CONSUL_PLACEHOLDER: tenant-9350e2fc-a1dd-4c65-8d40-1f75a2e080dd.voice.svc.cluster.local
  #BDS_CFG_DEV_GLOBALS_SFTP_PSW_PLACEHOLDER: pass
  #BDS_CFG_DEV_GLOBALS_SFTP_USR_PLACEHOLDER: user
  BDS_CFG_GIR_ES_PLACEHOLDER: ""
  BDS_CFG_GLOBALS_CME_GVP_PSW_PLACEHOLDER: password
  BDS_CFG_GLOBALS_CME_GVP_USER_PLACEHOLDER: default
  BDS_CFG_GLOBALS_CME_PSW_PLACEHOLDER: password
  BDS_CFG_GLOBALS_CME_USER_PLACEHOLDER: default
  BDS_CFG_GLOBALS_GIM_DB_HOST_PLACEHOLDER: postgres-postgresql.infra.svc.cluster.local
  BDS_CFG_GLOBALS_GIM_DB_NAME_PLACEHOLDER: gim
  BDS_CFG_GLOBALS_GIM_DB_PSW_PLACEHOLDER: gim
  BDS_CFG_GLOBALS_GIM_DB_USR_PLACEHOLDER: gim
  BDS_CFG_GLOBALS_GVP_DB_NAME_PLACEHOLDER: gvp_rs
  BDS_CFG_GLOBALS_GVP_DB_PL_EASTUS2_HOST_PLACEHOLDER: mssql-deployment.infra.svc.cluster.local
  BDS_CFG_GLOBALS_GVP_DB_PL_EASTUS2_NAME_PLACEHOLDER: gvp_rs
  BDS_CFG_GLOBALS_GVP_DB_PL_EASTUS2_PSW_PLACEHOLDER: gvp_rs_password
  BDS_CFG_GLOBALS_GVP_DB_PL_EASTUS2_USR_PLACEHOLDER: openshiftadmin
  BDS_CFG_GLOBALS_GVP_DB_PSW_PLACEHOLDER: db_password
  BDS_CFG_GLOBALS_GVP_DB_USER_PLACEHOLDER: openshiftadmin
  BDS_CFG_GLOBALS_GVP_DB_WESTUS2_HOST_PLACEHOLDER: mssql-deployment.infra.svc.cluster.local
  BDS_CFG_GLOBALS_GVP_DB_WESTUS2_NAME_PLACEHOLDER: gvp_rs
  BDS_CFG_GLOBALS_GVP_DB_WESTUS2_PSW_PLACEHOLDER: db_password
  BDS_CFG_GLOBALS_GVP_DB_WESTUS2_USR_PLACEHOLDER: openshiftadmin
  BDS_CFG_GWS_AUTH_HOST_PLACEHOLDER: http://gauth-auth.gauth.svc.cluster.local
  BDS_CFG_GWS_HOST_PLACEHOLDER: http://gws-service-proxy.gws.svc.cluster.local
  BDS_CFG_LEGACY_GLOBALS_SFTP_PSW_PLACEHOLDER: ""
  BDS_CFG_LEGACY_GLOBALS_SFTP_USR_PLACEHOLDER: ""
  BDS_CFG_SFTP_HOST_PLACEHOLDER: ""
  BDS_CFG_SFTP_PATH_PLACEHOLDER: ""
  BDS_CFG_SOURCEID_PLACEHOLDER: MULTICLOUD_PE