gws-ui-auth:          100.0.007.1355
gws-core-environment: 100.0.007.1927
gws-core-auth:        100.0.007.3692

postgres:
  host:     POSTGRES_ADDR
  db:       DB_NAME 

###############################################################################
# Values below recommended to save in secrets/deployment-secrets for privacy 
# 
# Don`t change values below if using secrets/deployment-secrets. 
# It will be read and replaced by values from secrets/deployment-secrets
###############################################################################
  username: gauth_pg_username
  password: gauth_pg_password


redis:
  password: gauth_redis_password

services:
  location: global_location
  secret:
    admin_username: gauth_admin_username
    admin_password: gauth_admin_password
    client_id:      gauth_gws_client_id
    client_secret:  gauth_gws_client_secret

  auth:
    jks:
      enabled: true
      sso:
        enabled: true
      secret:
        create: true

      # Convert keystore.jks file content to base64 ( cat keystore.jks | base64 ) and put the output here
      keyStore: jksStorage.jks

      keyStoreFileData: <key content>	
      # Keystore password
      keyStorePassword: gauth_jks_keyStorePassword
      # SSL key alias
      keyAlias: gws-auth-key
      # SSL key password
      keyPassword: gauth_jks_keyPassword
