gws-ui-auth:          100.0.007.1355
gws-core-environment: 100.0.007.1927
gws-core-auth:        100.0.007.3692

postgres:
  host:     POSTGRES_ADDR
  db:       DB_NAME 

###############################################################################
# Values below recommended to save in secrets/deployment-secrets for privacy 
# 
# Don`t change values below if using secrets/deployment-secrets. 
# It will be read and replaced by values from secrets/deployment-secrets
###############################################################################
  username: gauth_pg_username
  password: gauth_pg_password


redis:
  password: gauth_redis_password

services:
  location: global_location
  secret:
    admin_username: gauth_admin_username
    admin_password: gauth_admin_password
    client_id:      gauth_gws_client_id
    client_secret:  gauth_gws_client_secret

  auth:
    jks:
      enabled: true
      sso:
        enabled: true
      secret:
        create: true

      # Convert keystore.jks file content to base64 ( cat keystore.jks | base64 ) and put the output here
      keyStore: jksStorage.jks
      keyStoreFileData: MIIKsQIBAzCCCmoGCSqGSIb3DQEHAaCCClsEggpXMIIKUzCCBboGCSqGSIb3DQEHAaCCBasEggWnMIIFozCCBZ8GCyqGSIb3DQEMCgECoIIFQDCCBTwwZgYJKoZIhvcNAQUNMFkwOAYJKoZIhvcNAQUMMCsEFJsA2H3MpVREYW1+9z/pfJHWCYuqAgInEAIBIDAMBggqhkiG9w0CCQUAMB0GCWCGSAFlAwQBKgQQw34kFjkbuCV7N/+gOTnXDgSCBNCqQkNIYu76kjTiXDLl6TUzLXGuvVc2pn8X6V/gC8Et1V9nmK0HfvKxzK3Hr8OFVqKacTV8IetQPve+2UayflmAWPi4mXTBbRTtf7Ork88NMVuAMHoDQYIMwskJUEifzPnqD3o7ru2Rg3833SoszRKTvnQjIoSOEOZEZc/L0iWT1C+pbQ/Go6wboArlXIJTNcEui70tdJQTWl/5JWFPo4bU5NwXtwfh50Cu+6K+kZRvwQHsdA3UM093Mj1KDkQTEsWogewRmo5Pp5eGaZw/cvXFLoJjv+InY3fDU31rS8H7rspV3Q0s7wOG5nNUfamiJmDOsU+brcWa4iXSFsoNDuhT/bLqf+L18UX8yH/O/iMNWinD7xT/+t+leBBc29Upe8Mr4p/GH+f5bQH0rrwWYwmo8m4h3bgEqipy3/rh7DflAupRsgPxcEfl1rtrYwh0m2u5ipxTjgzIfpOtUpSTsEuLDIhbD9Z6jWfBWx4/MLP2xn/52ubptQhPazxDA8bnvuHoW9fwF4trijMP4e2tKNftWtYWLXXMe1PSSaqvyrhiqI9t5lwrYsJGd5dqtMrVKfzebQ0h7zrN9e1Pa2zG3cnH4elmiLCuctEhjcVO5v1cS8YXymyhWLSYDDIvUjZ8t2OM4DIZt7a2D1T6X/SR8TSMqKsPiTFkBramfMnSQOmprAMAtE+4PRSxjXjyltNr7SpXQJNf6p5zkzExkJq9/wjaW9CdLMvkGN/uVaJ1pJwNdhiz4qo45M7Dwr6lamaEn8pMBIfAEuPsiLZxjMl2abOBCAt2P98LMOO4RQ94k05h3raatOtMkifyMUMF+QPR4fdSeZisvsdnxnw0ym3E3oGaz04NIlD3GA8nTaUOFuQxTVYjG7EUcde43uK4dcxf2xu2YD9Dr0VprGcA3bsQ5XzKqLrVHg50itrpjFj/Mj5fvmofNPZ3kOXwra86fTCk1XmL5HRXvOkxGsquOTO9gpVQVesK4nPPRwi4NB7hGnPAI6BCSzfiUxrMufDiSIFC8n/xcmHscLVGwhqzJ/Tz2SNd/VGGEz9yPRGVlRI4F8pJ/T4G2gHdh2xf8wCSQrKto45xE4HO9HrWumgzl3ock5NSSusgg+Ebi4nQ63Vf4uIW4Hs+yQw4S1y5d7XewxpMOwH4OZESTgxQsIkj7Gc9AloBmcfwZbV0sByGi6geF9m06j4NexbvdJNC+KRKwdwrOFx7te3zcEZgmjH2KUGtV1HJT08IeR3GNzKfrTXXyLX3kceR51c+4FpGBx39qEUcMHchUaYqoiVnYkOk2WjrFH3EuFfW4wB6p1ilRcBK6e6bejDYGe3soz85fbnv099z1ZjFiCdP22r++vksTwZZhgfNAl4yUz+na8LTYaBCX84P3TMaQkZ294dF/6xXeOXelaFf8gVmxnaj+SrIqLrBm9NTJpGT9wUMYT5VQm0FTBhbjJX/H7QKyV44M4v0//1uIrcMvB0/1QjE/5z1xfrQKnhs/Gi8ILh1wArCbjxWrk0n5Q0Knceajou+xKdhE32C8lz46SdwOOd/ceBtclg8DyM8HTKbftQaJfYPLz3YFwi2wBlL1ys7Z4zu+e5HHjiem9TXuSIoVYljGIYR05fHob73WxhKr1A24EnwrqV1Fl2QhDFMMCcGCSqGSIb3DQEJFDEaHhgAZwB3AHMALQBhAHUAdABoAC0AawBlAHkwIQYJKoZIhvcNAQkVMRQEElRpbWUgMTY1NzYyMDgxMTY2NjCCBJEGCSqGSIb3DQEHBqCCBIIwggR+AgEAMIIEdwYJKoZIhvcNAQcBMGYGCSqGSIb3DQEFDTBZMDgGCSqGSIb3DQEFDDArBBTk/im4xTBzWo1OPJpidjWIIt8/lAICJxACASAwDAYIKoZIhvcNAgkFADAdBglghkgBZQMEASoEEMkRSbUEzhKv67K8/s6fXduAggQA0JEXtbw+PG8sqI5cDb/9SGkjEyyZufXt2wu2oHDYNEV5xeBKGbuHxHHMYTk954pJiEbMPzjGMJP9RlRG3Je4uVgoNDstTYkhdNJjLUHDLgy99l3D05KQfvXhQ++aQ5iGPx9hn2B+ZdDMhNW7JplWCg6oLl2bUMhveQL3MEUHJH4h4PE+5uvcsiWovUwa90zw+KV1RL75PUev4o/WvGPqJuGFG4Ztgwoo9iMgTWZAqD18dnB3/9dPrcDW9hY9ZtLw+knWGm4W2Y4hBfQscdxZ0GlUvMN3g6BP4GrupbmESN43YIb7WeD9FvazYAluBvulpBmL8Jz/7QzaZTXQEmkwC7N7+OHi627CsJzUSvD4sb/tiIZBZJOFkgizFH1cm9t3FtcK4VzHi/aG3vzldpO/VB/iNsjV92c2aT8LOfGBbN9TOg9NFEVc0BfeIhCwMlH0f9uCTGMY22SEUEuxk+pqxG6rz4lDt89B59W/6VCzXdfLTO/SbepgrNqRv31bj47VdFtxfVBqlxy5zokUUCONAixcJ2A2vaze0Yf+Zy2J5vCe4yaeb317FHSXiy1e8ZR0SF4aq6vSLH11Zro7Lv8wa1kuPa4l0tYlTDfJqihI4LayZcQtvgrKx9Gzr5aEfnvqYBuQtOhQvkTcVGzjiw5mZPOLC4d9E/VBLUDqofIPkljyctQbygFKzm4TYJBqJVoLwU2LN+FcitvdtV9jtEsDcknvPt66arxzY37iosvN06c3X7sQwiv3Rvb09pRYbTm7hlmoFOk9wd+Qn2sJ5O+kCG7gZxIqfV1SHWQsBgKdzUIGBPUSnoPB+mhqbW9OAun8qrl+TXGuoLC3krFJvq6C0XcGvS/5fJEZE/fJTsKMwmoTbcCN5CUPEVDrQOuvwbT1HszmP8wMgzUoJGlaGCAulPxfd0TKnJOBlvMZw+9cl3vZ7YO7j319z9mCrm2DBplhbHUWMYjIW3Q6VR4sekt9/n3BfmcPY0x1ILbIeU+cLnzwrbnTzDKfxkbv4UOUARVR55ySlkq5sq5G4kVq4VXHfOF1C+0hZeEFIpGqciEwHHX6PB8UFf2rPAa4Zkv6Ta8SvMO5e/wkg87tbVtZeLVzh4WbnwR4JwnaDwA5Ywu29bJ2sJkkFqDrlbGcvM8WcSrNl8DMEoBCPpgbTvGDhZTMXgcfRtScVJQQTk35HL11DLt/CR5fXjQj8O+Tnabc0ZjF4Qmb/pyqAhaItbO4mtPnOtE6j/BtT6rw+U2W9xIcFY80xqj7D4PPwBy1h2lYnx93uBpX5aZ//oBsXy/V8uwAGSfKRiNmI71BtoHleykt/C5eDAjDzeeCdsWKrTAWtUgGzXCRLPo88Yl0sgWn3B/23TA+MCEwCQYFKw4DAhoFAAQUzHgYD99xAuofHgKrED0LvPMWUDwEFAZrAs90xLbgVFi361YBf6ctL/ayAgMBhqA=
      
      #keyStoreFileData: <key content>	
      # Keystore password
      keyStorePassword: gauth_jks_keyStorePassword
      # SSL key alias
      keyAlias: gws-auth-key
      # SSL key password
      keyPassword: gauth_jks_keyPassword
