###############################################################################
# Define here application version if needed
###############################################################################

image:
  repository: mcr.microsoft.com/mssql/server
  tag: 2022-latest
  #repository: mcr.microsoft.com/mssql/server
  #tag: 2019-latest
