# no of instances to be created during starup default is 1
deployment:
  namespace: ${NS}
  replicaCount: 1

# override the registry from where the image will be deployed
image:
  registry: $IMAGE_REGISTRY
  pullPolicy: Always
  imagePullSecrets: "pullsecret"

loggingSidecar:
  enabled: true
  image:
    registry: fluent
    repository: fluent-bit

sipsLoggingSidecar:
  enabled: true
  image:
    registry: fluent
    repository: fluent-bit
    
# Set the redis port to be used.
context:
  envs:
    redis:
      port: 6379
    dnsServer: 127.0.0.1

# Set the consul volume to be mounted
secrets:
  consulACL:
    volumes:
    - name: consul-shared-secret
      secret:
        secretName: consul-voice-token

# pvc will be created for logs
volumes:
  pvcLog:
    create: true                                    # create defines whether a PVC needs to be created with the chart.
    claim: sip-log-pvc                              # Name of PVC
    volumeName:                                     # To bind this PVC to specified Persistent Volume.In case of Openshift, this is required only for NFS mounting and not needed for OFS.
    claimSize: 10Gi                                 # This field sets the storage size requested by PVC
    storageClass: csi-standard-rwx                  # This field sets the storage class requested by PVC
    mountPath: /opt/genesys/logs/volume             # Volume mount path for PV
       
  pvcJsonLog:
    create: true                                    # create defines whether a PVC needs to be created with the chart.
    claim: sip-json-log-pvc                         # Name of PVC
    volumeName:                                     # To bind this PVC to specified Persistent Volume.In case of Openshift, this is required only for NFS mounting and not needed for OFS.
    claimSize: 10Gi                                 # This field sets the storage size requested by PVC
    storageClass: csi-standard-rwx                  # This field sets the storage class requested by PVC
    mountPath: /opt/genesys/logs/sip_node/JSON      # Volume mount path for PV

  log:
    mountPath:                                      # Mount path for hostpath (/mnt/volume)

# Enable HPA and set the target CPU and memory for scale up and down
hpa:
  targetCPUPercent: 60
  targetMemoryPercent: 60
  enabled: true
  scaledownDisabled: true


prometheus:
    operator:
      enabled: false

prometheus:
    podMonitor:
      enabled: false
