###############################################################################
# Global GIM parameters
# https://all.docs.genesys.com/PEC-REP/Current/GIMPEGuide/ConfigureGIM
###############################################################################