###############################################################################
#
# Find more: https://github.com/bitnami/charts/tree/master/bitnami/postgresql
#
###############################################################################

global:
  storageClass: nfs-client
  
  postgresql:
    auth:
      database: "pg_bench"
      ####### Define custom password for postgres user if it`s needed ########
      postgresPassword: "secret"    #set desired secret, or it will generate random one
      # existingSecret: ""          #or specify existing secret to use
                                    #secret can be created manually by:
                                    # $ kubectl create secret generic <define_secret_name> --from-literal=postgres-password=<set_your_password>

#PostgreSQL architecture (standalone or replication)
architecture: standalone

primary:
  persistence:
    size: 3Gi
  extraEnvVars:
    - name:  POSTGRESQL_EXTRA_FLAGS
      value: "-c max_connections=512"

readReplicas:
  persistence:
    size: 3Gi
  extraEnvVars:
    - name:  POSTGRESQL_EXTRA_FLAGS
      value: "-c max_connections=512"

tls:                    #required for some services (eg. BDS)
  enabled: true
  autoGenerated: true

shmVolume:
  chmod:
    enabled: false

metrics:
  enabled: true #Start a prometheus exporter
  serviceMonitor:
    enabled: true