###############################################################################
# Define here application version if needed
###############################################################################

# image:
#   tag: 1.33.0-debian-10-r21