###############################################################################
# Additional GIM parameters
# https://all.docs.genesys.com/PEC-REP/Current/GIMPEGuide/ConfigureGIM
###############################################################################

image:
  tag: 100.0.116.2900  

tenant_id: t${tenant_sid}
tenant_uuid: $tenant_id

kafka:
  bootstrap: $KAFKA_ADDR:9092

db:
  jdbcUrl: jdbc:postgresql://${POSTGRES_ADDR}:5432/${gim_pgdb_etl_name}?${gim_pgdb_etl_user}&sslmode=prefer
  host: ${POSTGRES_ADDR}
  name: ${gim_pgdb_etl_name}
  username: ${gim_pgdb_etl_user}
  password: ${gim_pgdb_etl_password}
