###############################################################################
#
# Find more: https://www.consul.io/docs/k8s/helm#configuration-values
#
###############################################################################

global:
  name: consul
  tls:
    enabled: true
    httpsOnly: false
    caCert:
      secretName: consul-ca-cert
      # The key of the Kubernetes secret.
      secretKey: tls.crt
    caKey:
      # The name of the Kubernetes secret.
      secretName: consul-ca-key
      # The key of the Kubernetes secret.
      secretKey: tls.key
  acls:
    manageSystemACLs: true
client:
  enabled: true
connectInject:
  enabled: true
  replicas: 1
controller:
  enabled: true
syncCatalog:
  enabled: true
  toConsul: true
  toK8S: false
  addK8SNamespaceSuffix: false
server:
  storage: 1Gi
  replicas: 2
  securityContext:
    runAsUser: 0
    runAsNonRoot: false
    runAsGroup: 0  