###############################################################################
#
# Find more: https://github.com/bitnami/charts/tree/master/bitnami/redis-cluster
#
###############################################################################

volumePermissions:
  enabled: true

persistence:
  size: 2Gi

redis:
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
