###############################################################################
# Additional GSP parameters
# https://all.docs.genesys.com/PEC-REP/Current/GIMPEGuide/ConfigureGSP
###############################################################################
image:
  tag: 100.0.100.1400

job:
  storage:
    gspPrefix:    "s3p://BUCKET_NAME/{{ .Release.Name }}/"
    gcaSnapshots: "s3p://BUCKET_NAME/gca/"
    s3:
      endpoint:   "https://BUCKET_HOST:BUCKET_PORT"
      accessKey:  S3_ACCESS_KEY
      secretKey:  S3_SECRET_KEY
      pathStyleAccess: "true"
kafka:
  bootstrap: KAFKA_ADDR:9092