###############################################################################
# Global GCA parameters
# https://all.docs.genesys.com/PEC-REP/Current/GIMPEGuide/ConfigureGCA
###############################################################################