###############################################################################
# Global Designer DAS parameters
# https://all.docs.genesys.com/DES/Current/DESPEGuide/Configure#DAS_deployment_settings
###############################################################################
das:
  deployment:
    strategy: blue-green-service
    color: "green" # cutover value
  service:
    type: ClusterIP
    port: 8081
    targetPort: http
