###############################################################################
#
# Find more: 
# 
# https://github.com/opensearch-project/helm-charts/tree/main/charts/opensearch
#
###############################################################################

rbac:
  create: true
  serviceAccountAnnotations: {}
  serviceAccountName: "opensearch"

extraEnvs: 
  - name: DISABLE_SECURITY_PLUGIN
    value: "true"
  - name: DISABLE_INSTALL_DEMO_CONFIG
    value: "true"


extraInitContainers: 
  - name: ini-sysctl
    securityContext:
      runAsUser: 0
      privileged: true
    image: busybox:latest
    command: ['sysctl', '-w','vm.max_map_count=262144']

# for backward compability 
extraObjects:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        meta.helm.sh/release-name: opensearch
        meta.helm.sh/release-namespace: $NS
      labels:
        app.kubernetes.io/component: opensearch-cluster-master
        app.kubernetes.io/instance: opensearch
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: opensearch
        app.kubernetes.io/version: 1.3.0
        helm.sh/chart: opensearch-1.9.0
      name: elastic-es-http
      namespace: $NS
    spec:
      ports:
        - name: http
          port: 9200
          protocol: TCP
          targetPort: 9200
        - name: transport
          port: 9300
          protocol: TCP
          targetPort: 9300
      selector:
        app.kubernetes.io/instance: opensearch
        app.kubernetes.io/name: opensearch
      sessionAffinity: None
      type: ClusterIP
