###############################################################################
# Additional GCXI parameters
# https://all.docs.genesys.com/PEC-REP/Current/GCXIPEGuide/Configure
###############################################################################
gcxi:
  deployment:
    code: $tenant_sid
    region: ${LOCATION}
    tenantColor: 
    tenantId: $tenant_id
    tenantName: t$tenant_sid
    type: local
  env:
    TENANT_UUID: $tenant_id

    GCXI_GIM_DB:
      ## GCXI_GIM_DB.DSNDEF: definition for GCXI_GIM_DB DSN (connection to GIM database); format: DSN_NAME=GCXI_GIM_DB;DB_TYPE=;DB_TYPE_EX=;HOST=;PORT=;DB_NAME=;LOGIN=;PASSWORD=
      DSNDEF: DSN_NAME=GCXI_GIM_DB;DB_TYPE=POSTGRESQL;DB_TYPE_EX=PostgreSQL;HOST=${gim_db_host};PORT=5432;DB_NAME=${gim_db_name};LOGIN=;PASSWORD=;DRV_TYPE=JDBC;GCXI_QENGINE=ON
      LOGIN: $gim_db_user
      PASSWORD: $gim_db_pass

    IWD_DB:
      ## IWD_DB.DSNDEF: definition for IWD_DB DSN (connection to IWD database); format: DSN_NAME=IWD_DB;DB_TYPE=;DB_TYPE_EX=;HOST=;PORT=;DB_NAME=;LOGIN=;PASSWORD=
      DSNDEF: DSN_NAME=IWD_DB;DB_TYPE=POSTGRESQL;DB_TYPE_EX=PostgreSQL;HOST=${iwd_db_host};PORT=5432;DB_NAME=${iwd_db_name};LOGIN=;PASSWORD=;DRV_TYPE=JDBC;GCXI_QENGINE=ON
      LOGIN: $iwd_db_user
      PASSWORD: $iwd_db_pass

  ingress:
    external:
      host: web-gcxi-$tenant_sid.${DOMAIN}
    internal:
      host: web-gcxi-$tenant_sid-int.${DOMAIN}
