# no of instances to be created during starup default is 1
deployment:
  replicaCount: 1
  namespace: ${NS}

# override the registry from where the image will be deployed
image:
  registry: $IMAGE_REGISTRY
  pullPolicy: Always
  imagePullSecrets: "pullsecret"

# Set the redis port to be used. 
context:
  envs:
    redis:
      port: 6379

# Set the consul volume to be mounted
secrets:
  consulACL:
    volumes:
    - name: consul-shared-secret
      secret:
        secretName: consul-voice-token

# Enable HPA and set the target CPU and memory for scale up and down
hpa:
  targetCPUPercent: 60
  targetMemoryPercent: 60
  enabled: true
