###############################################################################
#
# Find more: https://github.com/bitnami/charts/tree/master/bitnami/redis
#
###############################################################################

architecture: standalone 