###############################################################################
# Additional Telemetry-service parameters
# https://all.docs.genesys.com/TLM/Current/TLMPEGuide/Configure#Override_Helm_chart_values
###############################################################################
tlm:
  image:
    tag: "100.0.005.1647"

  secrets:
      TELEMETRY_AUTH_CLIENT_SECRET: $TELEMETRY_AUTH_CLIENT_SECRET
  context:
    envs:
      TELEMETRY_AUTH_CLIENT_ID: $TELEMETRY_AUTH_CLIENT_ID